version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "automated-metals-ai-lambda"
s3_bucket = ""  # SAM will create this
s3_prefix = "automated-metals-ai"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
disable_rollback = true